name: Rust

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
      - tests/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
      - tests/**
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - id: rust-version
        run: echo "value=$(grep '^rust-version' Cargo.toml | sed 's/.*"\([^"]*\)".*/\1/')" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ steps.rust-version.outputs.value }}

      - run: cargo build --verbose
        shell: bash

      - run: cargo test --verbose
        shell: bash
